# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapps', '0001_initial'),
        ('coursesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ManyToManyField(to='loginapps.User'),
        ),
    ]
